install:
  - nvm install $(jq -r '.engines.node' package.json) && nvm use $(jq -r '.engines.node' package.json)
  - npm install -g "npm@$(jq -r '.engines.npm' package.json)"
  - npm ci
matrix:
  include:
    - os: linux
      language: android
      dist: trusty
      android:
        components:
          - build-tools-28.0.3
          - android-28
      before_install:
        - yes | sdkmanager "platforms;android-28"
        - yes | sdkmanager "build-tools;28.0.1"
      script:
        - "./android/gradlew assembleRelease -p android/"
    - os: osx
      osx_image: xcode9.3
      before_install:
        - brew install jq
        - brew cask install fastlane
      script:
        - fastlane ios test
after_success:
  - npm run coveralls
